spring:
  cloud:
    gateway:
      routes:
      - id: cookie_route
      - name: cookie_route2
        uri: http://example.org
        predicates:
        - Cookie=chocolate, ch.p
zuul:
  routes:
    users:
      path: /myusers/**
      sensitiveHeaders:
      url: https://downstream
